#!/bin//bash
#renamem    uses perl regexp  like:
#   rename 's/.jpg$/BlackValley2Gap.jpg/'  
# where $@ =    039.jpg  040.jpg
#   rename 's/mg_0//' 
# where $@ =   img_0104.jpg img_0105.jpg
#
# rename 's/\,//' "$@"
# rename 's/\,//' "$@"
# rename 's/mail.cibolo.usS//' "$@"
# rename 's/\://' "$@"
# rename 's/\=//' "$@"
#
# rename 's/^0/catalog_0/' "$@"
# rename 's/box_2/uncat_/' "$@"
# rename 's/img_00/owls_/' "$@"
# rename 's/usvi_trip/st-john-leinster-bay/' "$@"
rename 's/IMG_00/yardboard_TMK-/' "$@"
#rename 's/john_headshots_6/john_headshots_1/' "$@"
# rename 's/uncat_/uncat-/' "$@"
# rename 's/box_v/box_V/' "$@"
# rename 's/.JPG/box_.jpg/' "$@"
# rename 's/.jpg$/_Shannon2Cork.jpg/' "$@"
