Netlist(Freeze)
Netlist(Clear)
Netlist(Add,unnamed_net25,R15-1)
Netlist(Add,unnamed_net25,J2-3)
Netlist(Add,unnamed_net24,Q1-1)
Netlist(Add,unnamed_net24,R13-1)
Netlist(Add,unnamed_net24,R11-2)
Netlist(Add,unnamed_net23,Q2-1)
Netlist(Add,unnamed_net23,R12-1)
Netlist(Add,unnamed_net23,R10-2)
Netlist(Add,unnamed_net22,R8-2)
Netlist(Add,unnamed_net22,R7-1)
Netlist(Add,unnamed_net21,R7-2)
Netlist(Add,unnamed_net21,R6-2)
Netlist(Add,unnamed_net20,R6-1)
Netlist(Add,unnamed_net20,R5-2)
Netlist(Add,unnamed_net19,R5-1)
Netlist(Add,unnamed_net19,R4-1)
Netlist(Add,unnamed_net18,R4-2)
Netlist(Add,unnamed_net18,R3-1)
Netlist(Add,unnamed_net17,J3-18)
Netlist(Add,unnamed_net16,J3-17)
Netlist(Add,PA0_TIM_pulser,R12-2)
Netlist(Add,PA0_TIM_pulser,J3-16)
Netlist(Add,PA1_TIM_pulser,R13-2)
Netlist(Add,PA1_TIM_pulser,J3-15)
Netlist(Add,unnamed_net15,J3-14)
Netlist(Add,unnamed_net14,J3-13)
Netlist(Add,unnamed_net13,J3-11)
Netlist(Add,unnamed_net12,J3-10)
Netlist(Add,unnamed_net11,J3-9)
Netlist(Add,unnamed_net10,J3-8)
Netlist(Add,unnamed_net9,J3-7)
Netlist(Add,unnamed_net8,J3-6)
Netlist(Add,unnamed_net7,J3-5)
Netlist(Add,PA4_HV_sense,J3-12)
Netlist(Add,PA4_HV_sense,R14-2)
Netlist(Add,unnamed_net6,R8-1)
Netlist(Add,unnamed_net6,R14-1)
Netlist(Add,unnamed_net6,R9-2)
Netlist(Add,unnamed_net5,R3-2)
Netlist(Add,unnamed_net5,R2-2)
Netlist(Add,unnamed_net4,R2-1)
Netlist(Add,unnamed_net4,R1-2)
Netlist(Add,unnamed_net3,Q1-4)
Netlist(Add,unnamed_net3,Q1-2)
Netlist(Add,unnamed_net3,T1-5)
Netlist(Add,20V_IN,R15-2)
Netlist(Add,20V_IN,J2-1)
Netlist(Add,20V_IN,C12-1)
Netlist(Add,20V_IN,C11-1)
Netlist(Add,20V_IN,C10-1)
Netlist(Add,20V_IN,C9-1)
Netlist(Add,20V_IN,C8-1)
Netlist(Add,20V_IN,C7-1)
Netlist(Add,20V_IN,J3-4)
Netlist(Add,20V_IN,J3-3)
Netlist(Add,20V_IN,C6-1)
Netlist(Add,20V_IN,T1-7)
Netlist(Add,20V_IN,T1-8)
Netlist(Add,unnamed_net2,Q2-4)
Netlist(Add,unnamed_net2,Q2-2)
Netlist(Add,unnamed_net2,T1-10)
Netlist(Add,unnamed_net1,T1-1)
Netlist(Add,unnamed_net1,C2-1)
Netlist(Add,unnamed_net1,C1-1)
Netlist(Add,common,J2-2)
Netlist(Add,common,C12-2)
Netlist(Add,common,C11-2)
Netlist(Add,common,C10-2)
Netlist(Add,common,C9-2)
Netlist(Add,common,C8-2)
Netlist(Add,common,C7-2)
Netlist(Add,common,J3-2)
Netlist(Add,common,J3-1)
Netlist(Add,common,R10-1)
Netlist(Add,common,J3-19)
Netlist(Add,common,J3-20)
Netlist(Add,common,R11-1)
Netlist(Add,common,Q2-3)
Netlist(Add,common,Q1-3)
Netlist(Add,common,C6-2)
Netlist(Add,common,R9-1)
Netlist(Add,common,CT2-1)
Netlist(Add,common,C4-2)
Netlist(Add,common,T1-4)
Netlist(Add,common,D2-2)
Netlist(Add,common,C3-2)
Netlist(Add,doubler_out,C4-1)
Netlist(Add,doubler_out,R1-1)
Netlist(Add,doubler_out,CT1-1)
Netlist(Add,doubler_out,C3-1)
Netlist(Add,doubler_out,D1-1)
Netlist(Add,v2,C2-2)
Netlist(Add,v2,D2-1)
Netlist(Add,v2,C1-2)
Netlist(Add,v2,D1-2)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"R15","chip_2012_0805_N.fp","4.75K")
ElementSetAttr("R15","device","RC0805FR-074K75L")
ElementSetAttr("R15","manufacturer","unknown")
ElementSetAttr("R15","manufacturer_part_number","unknown")
ElementSetAttr("R15","vendor","unknown")
ElementSetAttr("R15","vendor_part_number","unknown")
ChangePinName("R15", 1, "1")
ChangePinName("R15", 2, "2")
ElementList(Need,"J2","DC-0500.fp","connect")
ElementSetAttr("J2","device","DC-0500")
ElementSetAttr("J2","manufacturer","unknown")
ElementSetAttr("J2","manufacturer_part_number","unknown")
ElementSetAttr("J2","vendor","unknown")
ElementSetAttr("J2","vendor_part_number","unknown")
ChangePinName("J2", 1, "1")
ChangePinName("J2", 3, "3")
ChangePinName("J2", 2, "2")
ElementList(Need,"Q2","SOT223_NXP.fp","NFET")
ElementSetAttr("Q2","device","BUK98150-55/CUF")
ElementSetAttr("Q2","manufacturer","unknown")
ElementSetAttr("Q2","manufacturer_part_number","unknown")
ElementSetAttr("Q2","vendor","unknown")
ElementSetAttr("Q2","vendor_part_number","unknown")
ChangePinName("Q2", 4, "D")
ChangePinName("Q2", 3, "S")
ChangePinName("Q2", 2, "D")
ChangePinName("Q2", 1, "G")
ElementList(Need,"Q1","SOT223_NXP.fp","NFET")
ElementSetAttr("Q1","device","BUK98150-55/CUF")
ElementSetAttr("Q1","manufacturer","unknown")
ElementSetAttr("Q1","manufacturer_part_number","unknown")
ElementSetAttr("Q1","vendor","unknown")
ElementSetAttr("Q1","vendor_part_number","unknown")
ChangePinName("Q1", 4, "D")
ChangePinName("Q1", 3, "S")
ChangePinName("Q1", 2, "D")
ChangePinName("Q1", 1, "G")
ElementList(Need,"C12","chip_2012_0805_N.fp","1 uF")
ElementSetAttr("C12","device","CL21B105KBFNFNE")
ElementSetAttr("C12","manufacturer","unknown")
ElementSetAttr("C12","manufacturer_part_number","unknown")
ElementSetAttr("C12","vendor","unknown")
ElementSetAttr("C12","vendor_part_number","unknown")
ChangePinName("C12", 2, "2")
ChangePinName("C12", 1, "1")
ElementList(Need,"C11","chip_3216_1206_N.fp","10 uF")
ElementSetAttr("C11","device","CL31B106KBHNNNE")
ElementSetAttr("C11","manufacturer","unknown")
ElementSetAttr("C11","manufacturer_part_number","unknown")
ElementSetAttr("C11","vendor","unknown")
ElementSetAttr("C11","vendor_part_number","unknown")
ChangePinName("C11", 2, "2")
ChangePinName("C11", 1, "1")
ElementList(Need,"C10","chip_2012_0805_N.fp","1 uF")
ElementSetAttr("C10","device","CL21B105KBFNFNE")
ElementSetAttr("C10","manufacturer","unknown")
ElementSetAttr("C10","manufacturer_part_number","unknown")
ElementSetAttr("C10","vendor","unknown")
ElementSetAttr("C10","vendor_part_number","unknown")
ChangePinName("C10", 2, "2")
ChangePinName("C10", 1, "1")
ElementList(Need,"R13","chip_2012_0805_N.fp","220")
ElementSetAttr("R13","device","MF-RES-0805-220")
ElementSetAttr("R13","manufacturer","unknown")
ElementSetAttr("R13","manufacturer_part_number","unknown")
ElementSetAttr("R13","vendor","unknown")
ElementSetAttr("R13","vendor_part_number","unknown")
ChangePinName("R13", 1, "1")
ChangePinName("R13", 2, "2")
ElementList(Need,"C9","cap_10mm_alum_smt.fp","220 uF")
ElementSetAttr("C9","device","UUX1E221MNL1GS")
ElementSetAttr("C9","manufacturer","unknown")
ElementSetAttr("C9","manufacturer_part_number","unknown")
ElementSetAttr("C9","vendor","unknown")
ElementSetAttr("C9","vendor_part_number","unknown")
ChangePinName("C9", 2, "-")
ChangePinName("C9", 1, "+")
ElementList(Need,"C8","cap_10mm_alum_smt.fp","220 uF")
ElementSetAttr("C8","device","UUX1E221MNL1GS")
ElementSetAttr("C8","manufacturer","unknown")
ElementSetAttr("C8","manufacturer_part_number","unknown")
ElementSetAttr("C8","vendor","unknown")
ElementSetAttr("C8","vendor_part_number","unknown")
ChangePinName("C8", 2, "-")
ChangePinName("C8", 1, "+")
ElementList(Need,"C7","cap_10mm_alum_smt.fp","220 uF")
ElementSetAttr("C7","device","UUX1E221MNL1GS")
ElementSetAttr("C7","manufacturer","unknown")
ElementSetAttr("C7","manufacturer_part_number","unknown")
ElementSetAttr("C7","vendor","unknown")
ElementSetAttr("C7","vendor_part_number","unknown")
ChangePinName("C7", 2, "-")
ChangePinName("C7", 1, "+")
ElementList(Need,"D2","diode_10mm.fp","3KV")
ElementSetAttr("D2","device","R3000-TP")
ElementSetAttr("D2","manufacturer","unknown")
ElementSetAttr("D2","manufacturer_part_number","unknown")
ElementSetAttr("D2","vendor","unknown")
ElementSetAttr("D2","vendor_part_number","unknown")
ChangePinName("D2", 1, "cathode")
ChangePinName("D2", 2, "anode")
ElementList(Need,"R12","chip_2012_0805_N.fp","220")
ElementSetAttr("R12","device","MF-RES-0805-220")
ElementSetAttr("R12","manufacturer","unknown")
ElementSetAttr("R12","manufacturer_part_number","unknown")
ElementSetAttr("R12","vendor","unknown")
ElementSetAttr("R12","vendor_part_number","unknown")
ChangePinName("R12", 1, "1")
ChangePinName("R12", 2, "2")
ElementList(Need,"R11","chip_2012_0805_N.fp","4.75K")
ElementSetAttr("R11","device","RC0805FR-074K75L")
ElementSetAttr("R11","manufacturer","unknown")
ElementSetAttr("R11","manufacturer_part_number","unknown")
ElementSetAttr("R11","vendor","unknown")
ElementSetAttr("R11","vendor_part_number","unknown")
ChangePinName("R11", 1, "1")
ChangePinName("R11", 2, "2")
ElementList(Need,"R10","chip_2012_0805_N.fp","4.75K")
ElementSetAttr("R10","device","RC0805FR-074K75L")
ElementSetAttr("R10","manufacturer","unknown")
ElementSetAttr("R10","manufacturer_part_number","unknown")
ElementSetAttr("R10","vendor","unknown")
ElementSetAttr("R10","vendor_part_number","unknown")
ChangePinName("R10", 1, "1")
ChangePinName("R10", 2, "2")
ElementList(Need,"R8","1206_HV.fp","475K")
ElementSetAttr("R8","device","RC1206FR-07475KL")
ElementSetAttr("R8","manufacturer","unknown")
ElementSetAttr("R8","manufacturer_part_number","unknown")
ElementSetAttr("R8","vendor","unknown")
ElementSetAttr("R8","vendor_part_number","unknown")
ChangePinName("R8", 1, "1")
ChangePinName("R8", 2, "2")
ElementList(Need,"R7","1206_HV.fp","475K")
ElementSetAttr("R7","device","RC1206FR-07475KL")
ElementSetAttr("R7","manufacturer","unknown")
ElementSetAttr("R7","manufacturer_part_number","unknown")
ElementSetAttr("R7","vendor","unknown")
ElementSetAttr("R7","vendor_part_number","unknown")
ChangePinName("R7", 1, "1")
ChangePinName("R7", 2, "2")
ElementList(Need,"R6","1206_HV.fp","475K")
ElementSetAttr("R6","device","RC1206FR-07475KL")
ElementSetAttr("R6","manufacturer","unknown")
ElementSetAttr("R6","manufacturer_part_number","unknown")
ElementSetAttr("R6","vendor","unknown")
ElementSetAttr("R6","vendor_part_number","unknown")
ChangePinName("R6", 1, "1")
ChangePinName("R6", 2, "2")
ElementList(Need,"R5","1206_HV.fp","475K")
ElementSetAttr("R5","device","RC1206FR-07475KL")
ElementSetAttr("R5","manufacturer","unknown")
ElementSetAttr("R5","manufacturer_part_number","unknown")
ElementSetAttr("R5","vendor","unknown")
ElementSetAttr("R5","vendor_part_number","unknown")
ChangePinName("R5", 1, "1")
ChangePinName("R5", 2, "2")
ElementList(Need,"R4","1206_HV.fp","475K")
ElementSetAttr("R4","device","RC1206FR-07475KL")
ElementSetAttr("R4","manufacturer","unknown")
ElementSetAttr("R4","manufacturer_part_number","unknown")
ElementSetAttr("R4","vendor","unknown")
ElementSetAttr("R4","vendor_part_number","unknown")
ChangePinName("R4", 1, "1")
ChangePinName("R4", 2, "2")
ElementList(Need,"R3","1206_HV.fp","475K")
ElementSetAttr("R3","device","RC1206FR-07475KL")
ElementSetAttr("R3","manufacturer","unknown")
ElementSetAttr("R3","manufacturer_part_number","unknown")
ElementSetAttr("R3","vendor","unknown")
ElementSetAttr("R3","vendor_part_number","unknown")
ChangePinName("R3", 1, "1")
ChangePinName("R3", 2, "2")
ElementList(Need,"C4","disk_cap_5mm_flat_flip.fp","4.7nF")
ElementSetAttr("C4","device","472-3KV")
ElementSetAttr("C4","manufacturer","unknown")
ElementSetAttr("C4","manufacturer_part_number","unknown")
ElementSetAttr("C4","vendor","unknown")
ElementSetAttr("C4","vendor_part_number","unknown")
ChangePinName("C4", 2, "2")
ChangePinName("C4", 1, "1")
ElementList(Need,"J3","ffc_zif_20.fp","connect")
ElementSetAttr("J3","device","ffc_zif_20")
ElementSetAttr("J3","manufacturer","unknown")
ElementSetAttr("J3","manufacturer_part_number","unknown")
ElementSetAttr("J3","vendor","unknown")
ElementSetAttr("J3","vendor_part_number","unknown")
ChangePinName("J3", 20, "20")
ChangePinName("J3", 19, "19")
ChangePinName("J3", 18, "18")
ChangePinName("J3", 17, "17")
ChangePinName("J3", 16, "16")
ChangePinName("J3", 15, "15")
ChangePinName("J3", 14, "14")
ChangePinName("J3", 13, "13")
ChangePinName("J3", 12, "12")
ChangePinName("J3", 11, "11")
ChangePinName("J3", 10, "10")
ChangePinName("J3", 9, "9")
ChangePinName("J3", 8, "8")
ChangePinName("J3", 7, "7")
ChangePinName("J3", 6, "6")
ChangePinName("J3", 5, "5")
ChangePinName("J3", 4, "4")
ChangePinName("J3", 3, "3")
ChangePinName("J3", 2, "2")
ChangePinName("J3", 1, "1")
ElementList(Need,"CT2","spring_coin_contact.fp","connect")
ElementSetAttr("CT2","device","terminal")
ElementSetAttr("CT2","manufacturer","unknown")
ElementSetAttr("CT2","manufacturer_part_number","unknown")
ElementSetAttr("CT2","vendor","unknown")
ElementSetAttr("CT2","vendor_part_number","unknown")
ChangePinName("CT2", 1, "terminal")
ElementList(Need,"CT1","spring_coin_contact.fp","connect")
ElementSetAttr("CT1","device","terminal")
ElementSetAttr("CT1","manufacturer","unknown")
ElementSetAttr("CT1","manufacturer_part_number","unknown")
ElementSetAttr("CT1","vendor","unknown")
ElementSetAttr("CT1","vendor_part_number","unknown")
ChangePinName("CT1", 1, "terminal")
ElementList(Need,"R14","chip_2012_0805_N.fp","220")
ElementSetAttr("R14","device","MF-RES-0805-220")
ElementSetAttr("R14","manufacturer","unknown")
ElementSetAttr("R14","manufacturer_part_number","unknown")
ElementSetAttr("R14","vendor","unknown")
ElementSetAttr("R14","vendor_part_number","unknown")
ChangePinName("R14", 1, "1")
ChangePinName("R14", 2, "2")
ElementList(Need,"R9","chip_2012_0805_N.fp","4.75K")
ElementSetAttr("R9","device","RC0805FR-074K75L")
ElementSetAttr("R9","manufacturer","unknown")
ElementSetAttr("R9","manufacturer_part_number","unknown")
ElementSetAttr("R9","vendor","unknown")
ElementSetAttr("R9","vendor_part_number","unknown")
ChangePinName("R9", 1, "1")
ChangePinName("R9", 2, "2")
ElementList(Need,"C6","chip_3216_1206_N.fp","10 uF")
ElementSetAttr("C6","device","CL31B106KBHNNNE")
ElementSetAttr("C6","manufacturer","unknown")
ElementSetAttr("C6","manufacturer_part_number","unknown")
ElementSetAttr("C6","vendor","unknown")
ElementSetAttr("C6","vendor_part_number","unknown")
ChangePinName("C6", 2, "2")
ChangePinName("C6", 1, "1")
ElementList(Need,"R2","1206_HV.fp","475K")
ElementSetAttr("R2","device","RC1206FR-07475KL")
ElementSetAttr("R2","manufacturer","unknown")
ElementSetAttr("R2","manufacturer_part_number","unknown")
ElementSetAttr("R2","vendor","unknown")
ElementSetAttr("R2","vendor_part_number","unknown")
ChangePinName("R2", 1, "1")
ChangePinName("R2", 2, "2")
ElementList(Need,"R1","1206_HV.fp","475K")
ElementSetAttr("R1","device","RC1206FR-07475KL")
ElementSetAttr("R1","manufacturer","unknown")
ElementSetAttr("R1","manufacturer_part_number","unknown")
ElementSetAttr("R1","vendor","unknown")
ElementSetAttr("R1","vendor_part_number","unknown")
ChangePinName("R1", 1, "1")
ChangePinName("R1", 2, "2")
ElementList(Need,"T1","xfmr_epc19_10.fp","xfmr")
ElementSetAttr("T1","device","CS1-HVT-EPC19-03")
ElementSetAttr("T1","manufacturer","unknown")
ElementSetAttr("T1","manufacturer_part_number","unknown")
ElementSetAttr("T1","vendor","unknown")
ElementSetAttr("T1","vendor_part_number","unknown")
ChangePinName("T1", 5, "2")
ChangePinName("T1", 7, "3")
ChangePinName("T1", 4, "4")
ChangePinName("T1", 8, "5")
ChangePinName("T1", 10, "6")
ChangePinName("T1", 1, "1")
ElementList(Need,"C2","disk_cap_5mm_flat_flip.fp","4.7nF")
ElementSetAttr("C2","device","472-3KV")
ElementSetAttr("C2","manufacturer","unknown")
ElementSetAttr("C2","manufacturer_part_number","unknown")
ElementSetAttr("C2","vendor","unknown")
ElementSetAttr("C2","vendor_part_number","unknown")
ChangePinName("C2", 2, "2")
ChangePinName("C2", 1, "1")
ElementList(Need,"C1","disk_cap_5mm_flat.fp","4.7nF")
ElementSetAttr("C1","device","472-3KV")
ElementSetAttr("C1","manufacturer","unknown")
ElementSetAttr("C1","manufacturer_part_number","unknown")
ElementSetAttr("C1","vendor","unknown")
ElementSetAttr("C1","vendor_part_number","unknown")
ChangePinName("C1", 2, "2")
ChangePinName("C1", 1, "1")
ElementList(Need,"C3","disk_cap_5mm_flat.fp","4.7nF")
ElementSetAttr("C3","device","472-3KV")
ElementSetAttr("C3","manufacturer","unknown")
ElementSetAttr("C3","manufacturer_part_number","unknown")
ElementSetAttr("C3","vendor","unknown")
ElementSetAttr("C3","vendor_part_number","unknown")
ChangePinName("C3", 2, "2")
ChangePinName("C3", 1, "1")
ElementList(Need,"D1","diode_10mm.fp","3KV")
ElementSetAttr("D1","device","R3000-TP")
ElementSetAttr("D1","manufacturer","unknown")
ElementSetAttr("D1","manufacturer_part_number","unknown")
ElementSetAttr("D1","vendor","unknown")
ElementSetAttr("D1","vendor_part_number","unknown")
ChangePinName("D1", 1, "cathode")
ChangePinName("D1", 2, "anode")
ElementList(Done)
