Netlist(Freeze)
Netlist(Clear)
Netlist(Add,3.3V,C10-2)
Netlist(Add,3.3V,C12-2)
Netlist(Add,3.3V,C11-2)
Netlist(Add,3.3V,U2-3)
Netlist(Add,PB8,U1-46)
Netlist(Add,PB9,U1-45)
Netlist(Add,unnamed_net41,U1-43)
Netlist(Add,unnamed_net40,U1-42)
Netlist(Add,unnamed_net39,U1-41)
Netlist(Add,unnamed_net38,U1-40)
Netlist(Add,unnamed_net37,U1-39)
Netlist(Add,unnamed_net36,U1-38)
Netlist(Add,unnamed_net35,U1-37)
Netlist(Add,unnamed_net34,U1-34)
Netlist(Add,unnamed_net33,U1-33)
Netlist(Add,unnamed_net32,U1-30)
Netlist(Add,unnamed_net31,U1-29)
Netlist(Add,unnamed_net30,U1-28)
Netlist(Add,unnamed_net29,U1-27)
Netlist(Add,unnamed_net28,U1-26)
Netlist(Add,unnamed_net27,U1-25)
Netlist(Add,unnamed_net26,U1-21)
Netlist(Add,unnamed_net25,U1-20)
Netlist(Add,unnamed_net24,U1-19)
Netlist(Add,unnamed_net23,U1-18)
Netlist(Add,unnamed_net22,U1-17)
Netlist(Add,unnamed_net21,U1-16)
Netlist(Add,unnamed_net20,U1-2)
Netlist(Add,NRESET,U1-7)
Netlist(Add,NRESET,S2-1)
Netlist(Add,unnamed_net19,J2-4)
Netlist(Add,USB_5V,U2-1)
Netlist(Add,USB_5V,J2-1)
Netlist(Add,unnamed_net18,J2-3)
Netlist(Add,unnamed_net18,R7-1)
Netlist(Add,unnamed_net17,U1-31)
Netlist(Add,unnamed_net17,R7-2)
Netlist(Add,unnamed_net16,J2-2)
Netlist(Add,unnamed_net16,R6-1)
Netlist(Add,unnamed_net15,U1-32)
Netlist(Add,unnamed_net15,R6-2)
Netlist(Add,unnamed_net14,J1-18)
Netlist(Add,unnamed_net13,J1-17)
Netlist(Add,PA0,U1-10)
Netlist(Add,PA0,J1-16)
Netlist(Add,PA1,U1-11)
Netlist(Add,PA1,J1-15)
Netlist(Add,PA2,U1-12)
Netlist(Add,PA2,J1-14)
Netlist(Add,PA3,U1-13)
Netlist(Add,PA3,J1-13)
Netlist(Add,PA4,U1-14)
Netlist(Add,PA4,J1-12)
Netlist(Add,PA5,U1-15)
Netlist(Add,PA5,J1-11)
Netlist(Add,unnamed_net12,J1-10)
Netlist(Add,unnamed_net11,J1-9)
Netlist(Add,unnamed_net10,J1-8)
Netlist(Add,unnamed_net9,J1-7)
Netlist(Add,unnamed_net8,J1-6)
Netlist(Add,20V_IN,J1-4)
Netlist(Add,20V_IN,J1-3)
Netlist(Add,unnamed_net7,U1-4)
Netlist(Add,unnamed_net7,C8-2)
Netlist(Add,unnamed_net7,U1-3)
Netlist(Add,unnamed_net7,X2-2)
Netlist(Add,unnamed_net6,C9-2)
Netlist(Add,unnamed_net6,X2-1)
Netlist(Add,unnamed_net5,S1-2)
Netlist(Add,unnamed_net5,U1-44)
Netlist(Add,unnamed_net5,R5-2)
Netlist(Add,unnamed_net4,U1-22)
Netlist(Add,unnamed_net4,C2-1)
Netlist(Add,unnamed_net3,U1-6)
Netlist(Add,unnamed_net3,C7-2)
Netlist(Add,unnamed_net3,X1-2)
Netlist(Add,unnamed_net2,C6-2)
Netlist(Add,unnamed_net2,U1-5)
Netlist(Add,unnamed_net2,X1-1)
Netlist(Add,unnamed_net1,L3-1)
Netlist(Add,unnamed_net1,U1-9)
Netlist(Add,unnamed_net1,C5-1)
Netlist(Add,com,C12-1)
Netlist(Add,com,C10-1)
Netlist(Add,com,C11-1)
Netlist(Add,com,U2-2)
Netlist(Add,com,J2-5)
Netlist(Add,com,J1-20)
Netlist(Add,com,J1-19)
Netlist(Add,com,J1-5)
Netlist(Add,com,J1-2)
Netlist(Add,com,J1-1)
Netlist(Add,com,C2-2)
Netlist(Add,com,C8-1)
Netlist(Add,com,C9-1)
Netlist(Add,com,C7-1)
Netlist(Add,com,C6-1)
Netlist(Add,com,U1-8)
Netlist(Add,com,S2-2)
Netlist(Add,com,C5-2)
Netlist(Add,com,U1-23)
Netlist(Add,com,C4-1)
Netlist(Add,com,U1-35)
Netlist(Add,com,C3-1)
Netlist(Add,com,U1-47)
Netlist(Add,com,R5-1)
Netlist(Add,com,C1-2)
Netlist(Add,Vdd,S1-1)
Netlist(Add,Vdd,U1-24)
Netlist(Add,Vdd,C4-2)
Netlist(Add,Vdd,C3-2)
Netlist(Add,Vdd,U1-36)
Netlist(Add,Vdd,U1-48)
Netlist(Add,Vdd,U1-1)
Netlist(Add,Vdd,L3-2)
Netlist(Add,Vdd,C1-1)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"C12","chip_1608_0603_N.fp","1 uF")
ElementSetAttr("C12","device","MF-CAP-0603-1uF")
ElementSetAttr("C12","manufacturer","unknown")
ElementSetAttr("C12","manufacturer_part_number","unknown")
ElementSetAttr("C12","vendor","unknown")
ElementSetAttr("C12","vendor_part_number","unknown")
ChangePinName("C12", 2, "2")
ChangePinName("C12", 1, "1")
ElementList(Need,"C10","chip_1608_0603_N.fp","0.1 uF")
ElementSetAttr("C10","device","MF-CAP-0603-0.1uF")
ElementSetAttr("C10","manufacturer","unknown")
ElementSetAttr("C10","manufacturer_part_number","unknown")
ElementSetAttr("C10","vendor","unknown")
ElementSetAttr("C10","vendor_part_number","unknown")
ChangePinName("C10", 2, "2")
ChangePinName("C10", 1, "1")
ElementList(Need,"C11","chip_1608_0603_N.fp","1 uF")
ElementSetAttr("C11","device","MF-CAP-0603-1uF")
ElementSetAttr("C11","manufacturer","unknown")
ElementSetAttr("C11","manufacturer_part_number","unknown")
ElementSetAttr("C11","vendor","unknown")
ElementSetAttr("C11","vendor_part_number","unknown")
ChangePinName("C11", 2, "2")
ChangePinName("C11", 1, "1")
ElementList(Need,"U2","SOT23-123.fp","3.3")
ElementSetAttr("U2","device","AP2120N-3.3TRG1")
ElementSetAttr("U2","manufacturer","unknown")
ElementSetAttr("U2","manufacturer_part_number","unknown")
ElementSetAttr("U2","vendor","unknown")
ElementSetAttr("U2","vendor_part_number","unknown")
ChangePinName("U2", 3, "out")
ChangePinName("U2", 2, "GND")
ChangePinName("U2", 1, "in")
ElementList(Need,"S1","unknown","unknown")
ElementSetAttr("S1","device","SWITCH_PUSHBUTTON_NO")
ElementSetAttr("S1","manufacturer","unknown")
ElementSetAttr("S1","manufacturer_part_number","unknown")
ElementSetAttr("S1","vendor","unknown")
ElementSetAttr("S1","vendor_part_number","unknown")
ChangePinName("S1", 2, "2")
ChangePinName("S1", 1, "1")
ElementList(Need,"U1","UFQFPN48.fp","unknown")
ElementSetAttr("U1","device","stm32f401cb")
ElementSetAttr("U1","manufacturer","unknown")
ElementSetAttr("U1","manufacturer_part_number","unknown")
ElementSetAttr("U1","vendor","unknown")
ElementSetAttr("U1","vendor_part_number","unknown")
ChangePinName("U1", 48, "VDD")
ChangePinName("U1", 47, "VSS")
ChangePinName("U1", 46, "PB9")
ChangePinName("U1", 45, "PB8")
ChangePinName("U1", 44, "BOOT0")
ChangePinName("U1", 43, "PB7")
ChangePinName("U1", 42, "PB6")
ChangePinName("U1", 41, "PB5")
ChangePinName("U1", 40, "PB4-NJTRST")
ChangePinName("U1", 39, "PB3-JTDO-SWO")
ChangePinName("U1", 38, "PA15")
ChangePinName("U1", 37, "PA14-JTCK-SWCLK")
ChangePinName("U1", 36, "VDD")
ChangePinName("U1", 35, "VSS")
ChangePinName("U1", 34, "PA13-JTMS-SWDIO")
ChangePinName("U1", 33, "PA12")
ChangePinName("U1", 32, "PA11")
ChangePinName("U1", 31, "PA10")
ChangePinName("U1", 30, "PA9")
ChangePinName("U1", 29, "PA8")
ChangePinName("U1", 28, "PB15")
ChangePinName("U1", 27, "PB14")
ChangePinName("U1", 26, "PB13")
ChangePinName("U1", 25, "PB12")
ChangePinName("U1", 24, "VDD")
ChangePinName("U1", 23, "VSS")
ChangePinName("U1", 22, "VCAP_1")
ChangePinName("U1", 21, "PB10")
ChangePinName("U1", 20, "PB2")
ChangePinName("U1", 19, "PB1")
ChangePinName("U1", 18, "PB0")
ChangePinName("U1", 17, "PA7")
ChangePinName("U1", 16, "PA6")
ChangePinName("U1", 15, "PA5")
ChangePinName("U1", 14, "PA4")
ChangePinName("U1", 13, "PA3")
ChangePinName("U1", 12, "PA1")
ChangePinName("U1", 11, "PA1")
ChangePinName("U1", 10, "PA0")
ChangePinName("U1", 9, "VDDA/VREF+")
ChangePinName("U1", 8, "VSSA/VREF-")
ChangePinName("U1", 7, "NRST")
ChangePinName("U1", 6, "PH1-OSC_OUT")
ChangePinName("U1", 5, "PH0-OSC_IN")
ChangePinName("U1", 4, "PC15-OSC32_OUT")
ChangePinName("U1", 3, "PC14-OSC32_IN")
ChangePinName("U1", 2, "PC13")
ChangePinName("U1", 1, "VBAT RTC")
ElementList(Need,"L3","unknown","unknown")
ElementSetAttr("L3","device","COIL")
ElementSetAttr("L3","manufacturer","unknown")
ElementSetAttr("L3","manufacturer_part_number","unknown")
ElementSetAttr("L3","vendor","unknown")
ElementSetAttr("L3","vendor_part_number","unknown")
ChangePinName("L3", 2, "2")
ChangePinName("L3", 1, "1")
ElementList(Need,"S2","unknown","unknown")
ElementSetAttr("S2","device","SWITCH_PUSHBUTTON_NO")
ElementSetAttr("S2","manufacturer","unknown")
ElementSetAttr("S2","manufacturer_part_number","unknown")
ElementSetAttr("S2","vendor","unknown")
ElementSetAttr("S2","vendor_part_number","unknown")
ChangePinName("S2", 2, "2")
ChangePinName("S2", 1, "1")
ElementList(Need,"J2","microUSB_AB_1.fp","unknown")
ElementSetAttr("J2","device","USB")
ElementSetAttr("J2","manufacturer","unknown")
ElementSetAttr("J2","manufacturer_part_number","unknown")
ElementSetAttr("J2","vendor","unknown")
ElementSetAttr("J2","vendor_part_number","unknown")
ChangePinName("J2", 5, "GND")
ChangePinName("J2", 4, "ID")
ChangePinName("J2", 3, "D+")
ChangePinName("J2", 2, "D-")
ChangePinName("J2", 1, "VCC")
ElementList(Need,"R7","0805_HV.fp","22")
ElementSetAttr("R7","device","RESISTOR")
ElementSetAttr("R7","manufacturer","unknown")
ElementSetAttr("R7","manufacturer_part_number","unknown")
ElementSetAttr("R7","vendor","unknown")
ElementSetAttr("R7","vendor_part_number","unknown")
ChangePinName("R7", 1, "1")
ChangePinName("R7", 2, "2")
ElementList(Need,"R6","0805_HV.fp","22")
ElementSetAttr("R6","device","RESISTOR")
ElementSetAttr("R6","manufacturer","unknown")
ElementSetAttr("R6","manufacturer_part_number","unknown")
ElementSetAttr("R6","vendor","unknown")
ElementSetAttr("R6","vendor_part_number","unknown")
ChangePinName("R6", 1, "1")
ChangePinName("R6", 2, "2")
ElementList(Need,"J1","ffc_zif_20.fp","unknown")
ElementSetAttr("J1","device","zif_connector")
ElementSetAttr("J1","manufacturer","unknown")
ElementSetAttr("J1","manufacturer_part_number","unknown")
ElementSetAttr("J1","vendor","unknown")
ElementSetAttr("J1","vendor_part_number","unknown")
ChangePinName("J1", 20, "20")
ChangePinName("J1", 19, "19")
ChangePinName("J1", 18, "18")
ChangePinName("J1", 17, "17")
ChangePinName("J1", 16, "16")
ChangePinName("J1", 15, "15")
ChangePinName("J1", 14, "14")
ChangePinName("J1", 13, "13")
ChangePinName("J1", 12, "12")
ChangePinName("J1", 11, "11")
ChangePinName("J1", 10, "10")
ChangePinName("J1", 9, "9")
ChangePinName("J1", 8, "8")
ChangePinName("J1", 7, "7")
ChangePinName("J1", 6, "6")
ChangePinName("J1", 5, "5")
ChangePinName("J1", 4, "4")
ChangePinName("J1", 3, "3")
ChangePinName("J1", 2, "2")
ChangePinName("J1", 1, "1")
ElementList(Need,"C9","0805.fp","9 pF")
ElementSetAttr("C9","device","CAPACITOR")
ElementSetAttr("C9","manufacturer","unknown")
ElementSetAttr("C9","manufacturer_part_number","unknown")
ElementSetAttr("C9","vendor","unknown")
ElementSetAttr("C9","vendor_part_number","unknown")
ChangePinName("C9", 2, "2")
ChangePinName("C9", 1, "1")
ElementList(Need,"C8","0805.fp","9 pF")
ElementSetAttr("C8","device","CAPACITOR")
ElementSetAttr("C8","manufacturer","unknown")
ElementSetAttr("C8","manufacturer_part_number","unknown")
ElementSetAttr("C8","vendor","unknown")
ElementSetAttr("C8","vendor_part_number","unknown")
ChangePinName("C8", 2, "2")
ChangePinName("C8", 1, "1")
ElementList(Need,"X2","2412.fp","32.78")
ElementSetAttr("X2","device","CRYSTAL")
ElementSetAttr("X2","manufacturer","unknown")
ElementSetAttr("X2","manufacturer_part_number","unknown")
ElementSetAttr("X2","vendor","unknown")
ElementSetAttr("X2","vendor_part_number","unknown")
ChangePinName("X2", 2, "2")
ChangePinName("X2", 1, "1")
ElementList(Need,"R5","unknown","100K")
ElementSetAttr("R5","device","RESISTOR")
ElementSetAttr("R5","manufacturer","unknown")
ElementSetAttr("R5","manufacturer_part_number","unknown")
ElementSetAttr("R5","vendor","unknown")
ElementSetAttr("R5","vendor_part_number","unknown")
ChangePinName("R5", 1, "1")
ChangePinName("R5", 2, "2")
ElementList(Need,"C2","unknown","4.7 uF")
ElementSetAttr("C2","device","CAPACITOR")
ElementSetAttr("C2","manufacturer","unknown")
ElementSetAttr("C2","manufacturer_part_number","unknown")
ElementSetAttr("C2","vendor","unknown")
ElementSetAttr("C2","vendor_part_number","unknown")
ChangePinName("C2", 2, "2")
ChangePinName("C2", 1, "1")
ElementList(Need,"C7","0805.fp","20 pF")
ElementSetAttr("C7","device","CAPACITOR")
ElementSetAttr("C7","manufacturer","unknown")
ElementSetAttr("C7","manufacturer_part_number","unknown")
ElementSetAttr("C7","vendor","unknown")
ElementSetAttr("C7","vendor_part_number","unknown")
ChangePinName("C7", 2, "2")
ChangePinName("C7", 1, "1")
ElementList(Need,"C6","0805.fp","20 pF")
ElementSetAttr("C6","device","CAPACITOR")
ElementSetAttr("C6","manufacturer","unknown")
ElementSetAttr("C6","manufacturer_part_number","unknown")
ElementSetAttr("C6","vendor","unknown")
ElementSetAttr("C6","vendor_part_number","unknown")
ChangePinName("C6", 2, "2")
ChangePinName("C6", 1, "1")
ElementList(Need,"X1","1812.fp","12MHz")
ElementSetAttr("X1","device","CRYSTAL")
ElementSetAttr("X1","manufacturer","unknown")
ElementSetAttr("X1","manufacturer_part_number","unknown")
ElementSetAttr("X1","vendor","unknown")
ElementSetAttr("X1","vendor_part_number","unknown")
ChangePinName("X1", 2, "2")
ChangePinName("X1", 1, "1")
ElementList(Need,"C5","1206.fp","unknown")
ElementSetAttr("C5","device","CAPACITOR")
ElementSetAttr("C5","manufacturer","unknown")
ElementSetAttr("C5","manufacturer_part_number","unknown")
ElementSetAttr("C5","vendor","unknown")
ElementSetAttr("C5","vendor_part_number","unknown")
ChangePinName("C5", 2, "2")
ChangePinName("C5", 1, "1")
ElementList(Need,"C4","unknown","unknown")
ElementSetAttr("C4","device","CAPACITOR")
ElementSetAttr("C4","manufacturer","unknown")
ElementSetAttr("C4","manufacturer_part_number","unknown")
ElementSetAttr("C4","vendor","unknown")
ElementSetAttr("C4","vendor_part_number","unknown")
ChangePinName("C4", 2, "2")
ChangePinName("C4", 1, "1")
ElementList(Need,"C3","1206.fp","unknown")
ElementSetAttr("C3","device","CAPACITOR")
ElementSetAttr("C3","manufacturer","unknown")
ElementSetAttr("C3","manufacturer_part_number","unknown")
ElementSetAttr("C3","vendor","unknown")
ElementSetAttr("C3","vendor_part_number","unknown")
ChangePinName("C3", 2, "2")
ChangePinName("C3", 1, "1")
ElementList(Need,"C1","unknown","unknown")
ElementSetAttr("C1","device","CAPACITOR")
ElementSetAttr("C1","manufacturer","unknown")
ElementSetAttr("C1","manufacturer_part_number","unknown")
ElementSetAttr("C1","vendor","unknown")
ElementSetAttr("C1","vendor_part_number","unknown")
ChangePinName("C1", 2, "2")
ChangePinName("C1", 1, "1")
ElementList(Done)
