import machine
import pyb
# Define pins so they can be set with a pin reference like:  pin10.value(1) on the fly.
pinA1 = machine.Pin(machine.Pin.cpu.A1, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA2 = machine.Pin(machine.Pin.cpu.A2, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA3 = machine.Pin(machine.Pin.cpu.A3, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA4 = machine.Pin(machine.Pin.cpu.A4, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA5 = machine.Pin(machine.Pin.cpu.A5, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA6 = machine.Pin(machine.Pin.cpu.A6, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA7 = machine.Pin(machine.Pin.cpu.A7, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA8 = machine.Pin(machine.Pin.cpu.A8, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA9 = machine.Pin(machine.Pin.cpu.A9, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA10 = machine.Pin(machine.Pin.cpu.A10, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA11 = machine.Pin(machine.Pin.cpu.A11, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA12 = machine.Pin(machine.Pin.cpu.A12, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA13 = machine.Pin(machine.Pin.cpu.A13, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA14 = machine.Pin(machine.Pin.cpu.A14, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA15 = machine.Pin(machine.Pin.cpu.A15, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)

pinB3 = machine.Pin(machine.Pin.cpu.B3, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB4 = machine.Pin(machine.Pin.cpu.B4, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB5 = machine.Pin(machine.Pin.cpu.B5, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB6 = machine.Pin(machine.Pin.cpu.B6, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB7 = machine.Pin(machine.Pin.cpu.B7, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB8 = machine.Pin(machine.Pin.cpu.B8, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB9 = machine.Pin(machine.Pin.cpu.B9, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB10 = machine.Pin(machine.Pin.cpu.B10, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB13 = machine.Pin(machine.Pin.cpu.B13, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB14 = machine.Pin(machine.Pin.cpu.B14, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB15 = machine.Pin(machine.Pin.cpu.B15, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)

count = 0
while ( count < 40):
    pinA12.value(0)
#    pinB5.value(0)
#    pinB3.value(0)
#    pinB4.value(0)
    pinB8.value(0)
    pinB9.value(0)
    pyb.delay(60)
    pinA12.value(1)
#    pinB5.value(1)
#    pinB3.value(1)
#    pinB4.value(1)
    pinB8.value(1)
    pinB9.value(1)
    pyb.delay(60)
    count = count + 1
