# main.py -- Define pins so they can be set with a pin reference like:  pin10.value(1) on the fly.
import machine
import pyb
#rtc=pyb.RTC()
#rtc.datetime()
#rtc.info()
uart = pyb.UART(2, 4800)
pyb.repl_uart(uart)
pinB8 = machine.Pin(machine.Pin.cpu.B8, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB9 = machine.Pin(machine.Pin.cpu.B9, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA8 = machine.Pin(machine.Pin.cpu.A8, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA5 = machine.Pin(machine.Pin.cpu.A5, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinA4 = machine.Pin(machine.Pin.cpu.A4, machine.Pin.OUT_PP, machine.Pin.PULL_NONE)
pinB8.value(0)
pinB9.value(1)
pinA8.value(0)
pinA5.value(1)
pinA4.value(1)
pyb.delay(200)
pinB8.value(1)
pinB9.value(0)
pinA8.value(1)
pinA5.value(0)
pinA4.value(0)
pyb.delay(200)
pinB8.value(0)
pinB9.value(1)
pinA8.value(0)
pinA5.value(1)
pinA4.value(1)
pyb.delay(200)
pinB8.value(1)
pinB9.value(0)
pinA8.value(1)
pinA5.value(0)
pinA4.value(0)
pyb.delay(200)
pinB8.value(0)
pinB9.value(1)
pinA8.value(0)
pinA5.value(1)
pinA4.value(1)
pyb.delay(200)
pinB8.value(1)
pinB9.value(0)
pinA8.value(1)
pinA5.value(0)
pinA4.value(0)
pyb.delay(200)
pinB8.value(0)
pinB9.value(1)
pinA8.value(0)
pinA5.value(1)
pinA4.value(1)
pyb.delay(200)
pinB8.value(1)
pinB9.value(0)
pinA8.value(1)
pinA5.value(0)
pinA4.value(0)
